import { api } from "@/lib/api-client";
import type { AccountRecord, AppType } from "@/features/auth/auth-types";

// An "account" is an APPLICATION registered against auth-service — makemerich,
// the knowledge ingest console, anything onboarded later — persisted in its own
// `app_accounts` collection. Deliberately NOT /auth/organizations: an
// organization is a tenant that users belong to, which is a different concept
// stored separately (see features/app_accounts.py in auth-service).
//
// All calls are platform-staff only (403 otherwise); the UI hides itself for
// non-staff, the server enforces it.
export const AccountsApi = {
  list: () => api.get<AccountRecord[]>("/auth/accounts").then((r) => r.data),

  /** account_id is GENERATED by auth-service, not supplied here — it is an
   *  authorization key (the value an application sends at login, and what
   *  downstream services scope their data on), so it must not be guessable.
   *  The created record carries the UUID to copy into that application. */
  create: (payload: {
    name: string;
    description?: string;
    app_type?: AppType;
    app_url?: string;
  }) => api.post<AccountRecord>("/auth/accounts", payload).then((r) => r.data),

  /** Partial update; account_id itself is immutable. */
  update: (
    accountId: string,
    changes: {
      name?: string;
      description?: string;
      app_type?: AppType;
      app_url?: string;
      enabled?: boolean;
    },
  ) => api.patch<AccountRecord>(`/auth/accounts/${accountId}`, changes).then((r) => r.data),

  remove: (accountId: string) => api.delete(`/auth/accounts/${accountId}`).then(() => undefined),
};
